"""
PDF Brief Generator — Phase 3
===============================
What this file does:
  - Reads the AI-generated brief JSON from Phase 2
  - Generates a clean, professional PDF report
  - Saves it to outputs/pdfs/ folder

Think of this as the "publisher" of the engine.
Phase 1 collected data. Phase 2 analyzed it.
Phase 3 packages it into something you can hand to anyone.

Run it:
  python outputs/pdf_generator.py --ticker TSLA
  python outputs/pdf_generator.py --ticker MSFT
"""

import json
import argparse
from pathlib import Path
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    Table, TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT

# ── Configuration ─────────────────────────────────────────────────────────────

INPUT_DIR  = Path("data/briefs")
OUTPUT_DIR = Path("outputs/pdfs")

# Brand colors — professional dark blue palette
COLOR_DARK      = colors.HexColor("#0A1628")   # Near black — headers
COLOR_PRIMARY   = colors.HexColor("#1B4F8A")   # Deep blue — section titles
COLOR_ACCENT    = colors.HexColor("#2E86C1")   # Medium blue — highlights
COLOR_LIGHT     = colors.HexColor("#EAF2FB")   # Light blue — backgrounds
COLOR_SUCCESS   = colors.HexColor("#1E8449")   # Green — positive signals
COLOR_WARNING   = colors.HexColor("#B7950B")   # Amber — risk flags
COLOR_BORDER    = colors.HexColor("#BDC3C7")   # Gray — dividers
COLOR_TEXT      = colors.HexColor("#2C3E50")   # Dark gray — body text
COLOR_MUTED     = colors.HexColor("#7F8C8D")   # Light gray — metadata


# ── Step 1: Load the brief JSON from Phase 2 ─────────────────────────────────

def load_brief(ticker):
    """Load the intelligence brief generated by Phase 2."""
    filepath = INPUT_DIR / f"{ticker.upper()}_brief.json"

    if not filepath.exists():
        raise FileNotFoundError(
            f"No brief found for {ticker.upper()}. "
            f"Run Phase 2 first: python engine/synthesizer.py --ticker {ticker}"
        )

    with open(filepath, encoding="utf-8") as f:
        data = json.load(f)

    # Handle both direct brief and wrapped brief
    brief = data.get("brief", data)
    if "company_name" not in brief:
        brief = data

    print(f"  Loaded brief for: {brief.get('company_name', ticker)}")
    return brief, data.get("generated_at", "")


# ── Step 2: Define PDF styles ─────────────────────────────────────────────────

def build_styles():
    """
    Define all the text styles used in the PDF.
    Think of these like CSS classes — each one controls
    font, size, color, and spacing for a specific element.
    """
    styles = getSampleStyleSheet()

    custom = {

        # Company name — big and bold at the top
        "CompanyName": ParagraphStyle(
            "CompanyName",
            fontName="Helvetica-Bold",
            fontSize=24,
            textColor=COLOR_DARK,
            spaceAfter=4,
            leading=28
        ),

        # Ticker and metadata line
        "MetaLine": ParagraphStyle(
            "MetaLine",
            fontName="Helvetica",
            fontSize=10,
            textColor=COLOR_MUTED,
            spaceAfter=2
        ),

        # "INTELLIGENCE BRIEF" label
        "BriefLabel": ParagraphStyle(
            "BriefLabel",
            fontName="Helvetica-Bold",
            fontSize=9,
            textColor=COLOR_ACCENT,
            spaceAfter=4,
            leading=12
        ),

        # One line summary — the hero statement
        "OneLiner": ParagraphStyle(
            "OneLiner",
            fontName="Helvetica-Oblique",
            fontSize=12,
            textColor=COLOR_TEXT,
            spaceAfter=6,
            leading=18,
            leftIndent=12,
            rightIndent=12
        ),

        # Section headers e.g. "FINANCIAL HEALTH"
        "SectionHeader": ParagraphStyle(
            "SectionHeader",
            fontName="Helvetica-Bold",
            fontSize=9,
            textColor=COLOR_PRIMARY,
            spaceBefore=14,
            spaceAfter=6,
            leading=12
        ),

        # Score badge e.g. "[STRONG]"
        "ScoreBadge": ParagraphStyle(
            "ScoreBadge",
            fontName="Helvetica-Bold",
            fontSize=9,
            textColor=COLOR_SUCCESS,
            spaceAfter=4
        ),

        # Regular body text
        "Body": ParagraphStyle(
            "Body",
            fontName="Helvetica",
            fontSize=9,
            textColor=COLOR_TEXT,
            spaceAfter=4,
            leading=14
        ),

        # Sub-labels e.g. "Revenue:"
        "SubLabel": ParagraphStyle(
            "SubLabel",
            fontName="Helvetica-Bold",
            fontSize=9,
            textColor=COLOR_TEXT,
            spaceAfter=2,
            leading=13
        ),

        # Bullet point items
        "Bullet": ParagraphStyle(
            "Bullet",
            fontName="Helvetica",
            fontSize=9,
            textColor=COLOR_TEXT,
            spaceAfter=4,
            leading=13,
            leftIndent=12
        ),

        # Risk flag items — amber colored
        "RiskBullet": ParagraphStyle(
            "RiskBullet",
            fontName="Helvetica",
            fontSize=9,
            textColor=COLOR_TEXT,
            spaceAfter=4,
            leading=13,
            leftIndent=12
        ),

        # Talking point items — slightly emphasized
        "TalkingPoint": ParagraphStyle(
            "TalkingPoint",
            fontName="Helvetica",
            fontSize=9,
            textColor=COLOR_TEXT,
            spaceAfter=6,
            leading=14,
            leftIndent=12
        ),

        # Footer text
        "Footer": ParagraphStyle(
            "Footer",
            fontName="Helvetica",
            fontSize=7,
            textColor=COLOR_MUTED,
            alignment=TA_CENTER
        ),
    }

    return custom


# ── Step 3: Build each section of the PDF ────────────────────────────────────

def build_header(brief, generated_at, styles):
    """Build the top header section — company name, ticker, date."""
    elements = []

    company = brief.get("company_name", "Unknown Company")
    ticker  = brief.get("ticker", "???")

    # Format the generated date nicely
    try:
        dt = datetime.fromisoformat(generated_at.replace("Z", "+00:00"))
        date_str = dt.strftime("%B %d, %Y")
    except Exception:
        date_str = datetime.now().strftime("%B %d, %Y")

    # "INTELLIGENCE BRIEF" label
    elements.append(Paragraph("COMPANY INTELLIGENCE BRIEF", styles["BriefLabel"]))

    # Company name
    elements.append(Paragraph(company, styles["CompanyName"]))

    # Ticker | Date line
    elements.append(Paragraph(
        f"<font color='#2E86C1'>{ticker}</font>"
        f"&nbsp;&nbsp;·&nbsp;&nbsp;"
        f"Generated {date_str}"
        f"&nbsp;&nbsp;·&nbsp;&nbsp;"
        f"Source: SEC EDGAR + Claude AI",
        styles["MetaLine"]
    ))

    # Thick divider line
    elements.append(Spacer(1, 8))
    elements.append(HRFlowable(
        width="100%",
        thickness=2,
        color=COLOR_PRIMARY,
        spaceAfter=10
    ))

    return elements


def build_summary(brief, styles):
    """Build the one-line summary section."""
    elements = []

    summary = brief.get("one_line_summary", "")
    if not summary:
        return elements

    elements.append(Paragraph("EXECUTIVE SUMMARY", styles["SectionHeader"]))

    # Light blue background box for the summary
    summary_table = Table(
        [[Paragraph(f'"{summary}"', styles["OneLiner"])]],
        colWidths=[6.5 * inch]
    )
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), COLOR_LIGHT),
        ("ROUNDEDCORNERS", [4]),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (-1, -1), 12),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
    ]))
    elements.append(summary_table)

    return elements


def build_financial_health(brief, styles):
    """Build the financial health section with score badge."""
    elements = []

    fh    = brief.get("financial_health", {})
    score = fh.get("score", "N/A").upper()

    # Score color — green for strong, amber for moderate, red for weak
    score_color = (
        "#1E8449" if "STRONG" in score else
        "#B7950B" if "MODERATE" in score else
        "#C0392B"
    )

    elements.append(Paragraph(
        f"FINANCIAL HEALTH &nbsp;&nbsp;"
        f"<font color='{score_color}'>[{score}]</font>",
        styles["SectionHeader"]
    ))

    elements.append(HRFlowable(
        width="100%", thickness=0.5,
        color=COLOR_BORDER, spaceAfter=6
    ))

    # Summary paragraph
    if fh.get("summary"):
        elements.append(Paragraph(fh["summary"], styles["Body"]))
        elements.append(Spacer(1, 4))

    # Revenue / Margins / Cash as a clean table
    rows = []
    for label, key in [
        ("Revenue", "revenue_trend"),
        ("Margins", "profitability"),
        ("Cash",    "cash_position")
    ]:
        value = fh.get(key, "")
        if value:
            rows.append([
                Paragraph(f"<b>{label}</b>", styles["SubLabel"]),
                Paragraph(value, styles["Body"])
            ])

    if rows:
        t = Table(rows, colWidths=[0.8 * inch, 5.7 * inch])
        t.setStyle(TableStyle([
            ("VALIGN",        (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING",    (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING",   (0, 0), (-1, -1), 0),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 0),
        ]))
        elements.append(t)

    return elements


def build_risk_flags(brief, styles):
    """Build risk flags section — numbered list with warning indicators."""
    elements = []

    risks = brief.get("risk_flags", [])
    if not risks:
        return elements

    elements.append(Paragraph("RISK FLAGS", styles["SectionHeader"]))
    elements.append(HRFlowable(
        width="100%", thickness=0.5,
        color=COLOR_BORDER, spaceAfter=6
    ))

    for i, risk in enumerate(risks, 1):
        elements.append(Paragraph(
            f"<font color='#B7950B'><b>⚠ {i}.</b></font>  {risk}",
            styles["RiskBullet"]
        ))

    return elements


def build_strategic_moves(brief, styles):
    """Build strategic moves section."""
    elements = []

    moves = brief.get("strategic_moves", [])
    if not moves:
        return elements

    elements.append(Paragraph("STRATEGIC MOVES", styles["SectionHeader"]))
    elements.append(HRFlowable(
        width="100%", thickness=0.5,
        color=COLOR_BORDER, spaceAfter=6
    ))

    for i, move in enumerate(moves, 1):
        elements.append(Paragraph(
            f"<font color='#1B4F8A'><b>→ {i}.</b></font>  {move}",
            styles["Bullet"]
        ))

    return elements


def build_talking_points(brief, styles):
    """Build talking points section — the most actionable part."""
    elements = []

    points = brief.get("talking_points", [])
    if not points:
        return elements

    elements.append(Paragraph("TALKING POINTS", styles["SectionHeader"]))
    elements.append(HRFlowable(
        width="100%", thickness=0.5,
        color=COLOR_BORDER, spaceAfter=6
    ))

    elements.append(Paragraph(
        "Use these in your next interview, sales call, or board meeting:",
        styles["Body"]
    ))
    elements.append(Spacer(1, 4))

    for i, point in enumerate(points, 1):
        # Each talking point in its own light box
        point_table = Table(
            [[Paragraph(
                f"<font color='#1B4F8A'><b>{i}</b></font>  {point}",
                styles["TalkingPoint"]
            )]],
            colWidths=[6.5 * inch]
        )
        point_table.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), colors.HexColor("#F4F6F7")),
            ("TOPPADDING",    (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING",   (0, 0), (-1, -1), 10),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
            ("LINEBELOW",     (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ]))
        elements.append(point_table)
        elements.append(Spacer(1, 4))

    return elements


def build_footer(styles):
    """Build the footer with disclaimer."""
    elements = []

    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(
        width="100%", thickness=0.5,
        color=COLOR_BORDER, spaceAfter=6
    ))
    elements.append(Paragraph(
        "Generated by Company Intelligence Engine · "
        "Built by Abhishek Sahay · "
        "Source: SEC EDGAR public filings · "
        "AI Analysis: Claude (Anthropic) · "
        "For informational purposes only — not financial advice.",
        styles["Footer"]
    ))

    return elements


# ── Step 4: Assemble and generate the PDF ────────────────────────────────────

def generate_pdf(ticker):
    """
    Main function — loads the brief and builds the full PDF.
    Uses ReportLab's Platypus framework which works like building
    blocks — each section is a list of elements stacked vertically.
    """
    print(f"\n{'='*50}")
    print(f"  PDF Generator — Phase 3")
    print(f"  Ticker: {ticker.upper()}")
    print(f"{'='*50}\n")

    # Load brief data
    print("[1/3] Loading intelligence brief...")
    brief, generated_at = load_brief(ticker)

    # Set up output file
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    company_slug = brief.get("company_name", ticker).replace(" ", "_").replace(",", "")
    output_path  = OUTPUT_DIR / f"{ticker.upper()}_Intelligence_Brief.pdf"

    # Build styles
    styles = build_styles()

    # Create PDF document
    print("[2/3] Building PDF...")
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch
    )

    # Assemble all sections
    elements = []
    elements += build_header(brief, generated_at, styles)
    elements += build_summary(brief, styles)
    elements += build_financial_health(brief, styles)
    elements += build_risk_flags(brief, styles)
    elements += build_strategic_moves(brief, styles)
    elements += build_talking_points(brief, styles)
    elements += build_footer(styles)

    # Generate the PDF
    doc.build(elements)

    print(f"[3/3] PDF saved to: {output_path}")
    print(f"\n  Done! Open this file to see your intelligence brief:")
    print(f"  {output_path.absolute()}")
    print(f"\n  Ready for Phase 4 — Web Dashboard")

    return output_path


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate PDF intelligence brief from AI analysis"
    )
    parser.add_argument(
        "--ticker",
        required=True,
        help="Stock ticker e.g. TSLA, MSFT, AAPL"
    )
    args = parser.parse_args()
    generate_pdf(args.ticker)